// Copyright 2025 The axfor Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compare_CompareResult int32

const (
	Compare_EQUAL     Compare_CompareResult = 0
	Compare_GREATER   Compare_CompareResult = 1
	Compare_LESS      Compare_CompareResult = 2
	Compare_NOT_EQUAL Compare_CompareResult = 3
)

// Enum value maps for Compare_CompareResult.
var (
	Compare_CompareResult_name = map[int32]string{
		0: "EQUAL",
		1: "GREATER",
		2: "LESS",
		3: "NOT_EQUAL",
	}
	Compare_CompareResult_value = map[string]int32{
		"EQUAL":     0,
		"GREATER":   1,
		"LESS":      2,
		"NOT_EQUAL": 3,
	}
)

func (x Compare_CompareResult) Enum() *Compare_CompareResult {
	p := new(Compare_CompareResult)
	*p = x
	return p
}

func (x Compare_CompareResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareResult) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_raft_proto_enumTypes[0].Descriptor()
}

func (Compare_CompareResult) Type() protoreflect.EnumType {
	return &file_internal_proto_raft_proto_enumTypes[0]
}

func (x Compare_CompareResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareResult.Descriptor instead.
func (Compare_CompareResult) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{3, 0}
}

type Compare_CompareTarget int32

const (
	Compare_VERSION Compare_CompareTarget = 0
	Compare_CREATE  Compare_CompareTarget = 1
	Compare_MOD     Compare_CompareTarget = 2
	Compare_VALUE   Compare_CompareTarget = 3
	Compare_LEASE   Compare_CompareTarget = 4
)

// Enum value maps for Compare_CompareTarget.
var (
	Compare_CompareTarget_name = map[int32]string{
		0: "VERSION",
		1: "CREATE",
		2: "MOD",
		3: "VALUE",
		4: "LEASE",
	}
	Compare_CompareTarget_value = map[string]int32{
		"VERSION": 0,
		"CREATE":  1,
		"MOD":     2,
		"VALUE":   3,
		"LEASE":   4,
	}
)

func (x Compare_CompareTarget) Enum() *Compare_CompareTarget {
	p := new(Compare_CompareTarget)
	*p = x
	return p
}

func (x Compare_CompareTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_raft_proto_enumTypes[1].Descriptor()
}

func (Compare_CompareTarget) Type() protoreflect.EnumType {
	return &file_internal_proto_raft_proto_enumTypes[1]
}

func (x Compare_CompareTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareTarget.Descriptor instead.
func (Compare_CompareTarget) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{3, 1}
}

type Op_OpType int32

const (
	Op_PUT    Op_OpType = 0
	Op_DELETE Op_OpType = 1
	Op_RANGE  Op_OpType = 2
)

// Enum value maps for Op_OpType.
var (
	Op_OpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
		2: "RANGE",
	}
	Op_OpType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
		"RANGE":  2,
	}
)

func (x Op_OpType) Enum() *Op_OpType {
	p := new(Op_OpType)
	*p = x
	return p
}

func (x Op_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_raft_proto_enumTypes[2].Descriptor()
}

func (Op_OpType) Type() protoreflect.EnumType {
	return &file_internal_proto_raft_proto_enumTypes[2]
}

func (x Op_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op_OpType.Descriptor instead.
func (Op_OpType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{4, 0}
}

// RaftMessage is the top-level message for Raft entries
// Supports both single operations and batched operations
type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RaftMessage_Single
	//	*RaftMessage_Batch
	Payload       isRaftMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_internal_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessage) GetPayload() isRaftMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RaftMessage) GetSingle() *RaftOperation {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_Single); ok {
			return x.Single
		}
	}
	return nil
}

func (x *RaftMessage) GetBatch() *BatchOperation {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isRaftMessage_Payload interface {
	isRaftMessage_Payload()
}

type RaftMessage_Single struct {
	Single *RaftOperation `protobuf:"bytes,1,opt,name=single,proto3,oneof"` // Single operation
}

type RaftMessage_Batch struct {
	Batch *BatchOperation `protobuf:"bytes,2,opt,name=batch,proto3,oneof"` // Batch of operations
}

func (*RaftMessage_Single) isRaftMessage_Payload() {}

func (*RaftMessage_Batch) isRaftMessage_Payload() {}

// BatchOperation represents multiple operations batched into a single Raft entry
// This provides 2-5x additional throughput improvement over individual operations
type BatchOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*RaftOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"` // All operations in this batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperation) Reset() {
	*x = BatchOperation{}
	mi := &file_internal_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperation) ProtoMessage() {}

func (x *BatchOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperation.ProtoReflect.Descriptor instead.
func (*BatchOperation) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *BatchOperation) GetOperations() []*RaftOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

// RaftOperation represents an operation to be committed through Raft
// This replaces the JSON-based RaftOperation struct for better performance
type RaftOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation type: PUT, DELETE, LEASE_GRANT, LEASE_REVOKE, TXN
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Key-value operation fields
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	LeaseId  int64  `protobuf:"varint,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RangeEnd string `protobuf:"bytes,5,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	SeqNum   string `protobuf:"bytes,6,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"` // for sync wait
	// Lease operation fields
	Ttl int64 `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Transaction operation fields
	Compares      []*Compare `protobuf:"bytes,8,rep,name=compares,proto3" json:"compares,omitempty"`
	ThenOps       []*Op      `protobuf:"bytes,9,rep,name=then_ops,json=thenOps,proto3" json:"then_ops,omitempty"`
	ElseOps       []*Op      `protobuf:"bytes,10,rep,name=else_ops,json=elseOps,proto3" json:"else_ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftOperation) Reset() {
	*x = RaftOperation{}
	mi := &file_internal_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftOperation) ProtoMessage() {}

func (x *RaftOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftOperation.ProtoReflect.Descriptor instead.
func (*RaftOperation) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RaftOperation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RaftOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RaftOperation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RaftOperation) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *RaftOperation) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

func (x *RaftOperation) GetSeqNum() string {
	if x != nil {
		return x.SeqNum
	}
	return ""
}

func (x *RaftOperation) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *RaftOperation) GetCompares() []*Compare {
	if x != nil {
		return x.Compares
	}
	return nil
}

func (x *RaftOperation) GetThenOps() []*Op {
	if x != nil {
		return x.ThenOps
	}
	return nil
}

func (x *RaftOperation) GetElseOps() []*Op {
	if x != nil {
		return x.ElseOps
	}
	return nil
}

// Compare represents a transaction comparison
type Compare struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Key    string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Result Compare_CompareResult  `protobuf:"varint,2,opt,name=result,proto3,enum=raftpb.Compare_CompareResult" json:"result,omitempty"`
	Target Compare_CompareTarget  `protobuf:"varint,3,opt,name=target,proto3,enum=raftpb.Compare_CompareTarget" json:"target,omitempty"`
	// Target value (union type)
	//
	// Types that are valid to be assigned to TargetUnion:
	//
	//	*Compare_Version
	//	*Compare_CreateRevision
	//	*Compare_ModRevision
	//	*Compare_Value
	//	*Compare_Lease
	TargetUnion   isCompare_TargetUnion `protobuf_oneof:"target_union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_internal_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *Compare) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Compare) GetResult() Compare_CompareResult {
	if x != nil {
		return x.Result
	}
	return Compare_EQUAL
}

func (x *Compare) GetTarget() Compare_CompareTarget {
	if x != nil {
		return x.Target
	}
	return Compare_VERSION
}

func (x *Compare) GetTargetUnion() isCompare_TargetUnion {
	if x != nil {
		return x.TargetUnion
	}
	return nil
}

func (x *Compare) GetVersion() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_Version); ok {
			return x.Version
		}
	}
	return 0
}

func (x *Compare) GetCreateRevision() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_CreateRevision); ok {
			return x.CreateRevision
		}
	}
	return 0
}

func (x *Compare) GetModRevision() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_ModRevision); ok {
			return x.ModRevision
		}
	}
	return 0
}

func (x *Compare) GetValue() []byte {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Compare) GetLease() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_Lease); ok {
			return x.Lease
		}
	}
	return 0
}

type isCompare_TargetUnion interface {
	isCompare_TargetUnion()
}

type Compare_Version struct {
	Version int64 `protobuf:"varint,4,opt,name=version,proto3,oneof"`
}

type Compare_CreateRevision struct {
	CreateRevision int64 `protobuf:"varint,5,opt,name=create_revision,json=createRevision,proto3,oneof"`
}

type Compare_ModRevision struct {
	ModRevision int64 `protobuf:"varint,6,opt,name=mod_revision,json=modRevision,proto3,oneof"`
}

type Compare_Value struct {
	Value []byte `protobuf:"bytes,7,opt,name=value,proto3,oneof"`
}

type Compare_Lease struct {
	Lease int64 `protobuf:"varint,8,opt,name=lease,proto3,oneof"`
}

func (*Compare_Version) isCompare_TargetUnion() {}

func (*Compare_CreateRevision) isCompare_TargetUnion() {}

func (*Compare_ModRevision) isCompare_TargetUnion() {}

func (*Compare_Value) isCompare_TargetUnion() {}

func (*Compare_Lease) isCompare_TargetUnion() {}

// Op represents a transaction operation
type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Op_OpType              `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.Op_OpType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	RangeEnd      string                 `protobuf:"bytes,4,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	Lease         int64                  `protobuf:"varint,5,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_internal_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *Op) GetType() Op_OpType {
	if x != nil {
		return x.Type
	}
	return Op_PUT
}

func (x *Op) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Op) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Op) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

func (x *Op) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

// StoreSnapshot represents a complete snapshot of the KV store state
// (renamed to avoid conflict with raft.Snapshot)
type StoreSnapshot struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Revision      int64                     `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`                                                                                    // Current revision
	KvData        map[string]*KeyValueProto `protobuf:"bytes,2,rep,name=kv_data,json=kvData,proto3" json:"kv_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // All key-value pairs
	Leases        map[int64]*LeaseProto     `protobuf:"bytes,3,rep,name=leases,proto3" json:"leases,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`              // All leases
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSnapshot) Reset() {
	*x = StoreSnapshot{}
	mi := &file_internal_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSnapshot) ProtoMessage() {}

func (x *StoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSnapshot.ProtoReflect.Descriptor instead.
func (*StoreSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *StoreSnapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *StoreSnapshot) GetKvData() map[string]*KeyValueProto {
	if x != nil {
		return x.KvData
	}
	return nil
}

func (x *StoreSnapshot) GetLeases() map[int64]*LeaseProto {
	if x != nil {
		return x.Leases
	}
	return nil
}

// KeyValueProto represents a key-value pair in Protobuf
type KeyValueProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreateRevision int64                  `protobuf:"varint,3,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	ModRevision    int64                  `protobuf:"varint,4,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	Version        int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Lease          int64                  `protobuf:"varint,6,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValueProto) Reset() {
	*x = KeyValueProto{}
	mi := &file_internal_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueProto) ProtoMessage() {}

func (x *KeyValueProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueProto.ProtoReflect.Descriptor instead.
func (*KeyValueProto) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValueProto) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValueProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValueProto) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValueProto) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *KeyValueProto) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValueProto) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

// LeaseProto represents a lease in Protobuf
type LeaseProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ttl               int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	GrantTimeUnixNano int64                  `protobuf:"varint,3,opt,name=grant_time_unix_nano,json=grantTimeUnixNano,proto3" json:"grant_time_unix_nano,omitempty"` // Time as Unix nanoseconds
	Keys              []string               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`                                                         // Associated keys
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaseProto) Reset() {
	*x = LeaseProto{}
	mi := &file_internal_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseProto) ProtoMessage() {}

func (x *LeaseProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseProto.ProtoReflect.Descriptor instead.
func (*LeaseProto) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseProto) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *LeaseProto) GetGrantTimeUnixNano() int64 {
	if x != nil {
		return x.GrantTimeUnixNano
	}
	return 0
}

func (x *LeaseProto) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_internal_proto_raft_proto protoreflect.FileDescriptor

const file_internal_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/raft.proto\x12\x06raftpb\"y\n" +
	"\vRaftMessage\x12/\n" +
	"\x06single\x18\x01 \x01(\v2\x15.raftpb.RaftOperationH\x00R\x06single\x12.\n" +
	"\x05batch\x18\x02 \x01(\v2\x16.raftpb.BatchOperationH\x00R\x05batchB\t\n" +
	"\apayload\"G\n" +
	"\x0eBatchOperation\x125\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x15.raftpb.RaftOperationR\n" +
	"operations\"\xa9\x02\n" +
	"\rRaftOperation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\x03R\aleaseId\x12\x1b\n" +
	"\trange_end\x18\x05 \x01(\tR\brangeEnd\x12\x17\n" +
	"\aseq_num\x18\x06 \x01(\tR\x06seqNum\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x03R\x03ttl\x12+\n" +
	"\bcompares\x18\b \x03(\v2\x0f.raftpb.CompareR\bcompares\x12%\n" +
	"\bthen_ops\x18\t \x03(\v2\n" +
	".raftpb.OpR\athenOps\x12%\n" +
	"\belse_ops\x18\n" +
	" \x03(\v2\n" +
	".raftpb.OpR\aelseOps\"\xc0\x03\n" +
	"\aCompare\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x06result\x18\x02 \x01(\x0e2\x1d.raftpb.Compare.CompareResultR\x06result\x125\n" +
	"\x06target\x18\x03 \x01(\x0e2\x1d.raftpb.Compare.CompareTargetR\x06target\x12\x1a\n" +
	"\aversion\x18\x04 \x01(\x03H\x00R\aversion\x12)\n" +
	"\x0fcreate_revision\x18\x05 \x01(\x03H\x00R\x0ecreateRevision\x12#\n" +
	"\fmod_revision\x18\x06 \x01(\x03H\x00R\vmodRevision\x12\x16\n" +
	"\x05value\x18\a \x01(\fH\x00R\x05value\x12\x16\n" +
	"\x05lease\x18\b \x01(\x03H\x00R\x05lease\"@\n" +
	"\rCompareResult\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\v\n" +
	"\aGREATER\x10\x01\x12\b\n" +
	"\x04LESS\x10\x02\x12\r\n" +
	"\tNOT_EQUAL\x10\x03\"G\n" +
	"\rCompareTarget\x12\v\n" +
	"\aVERSION\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\a\n" +
	"\x03MOD\x10\x02\x12\t\n" +
	"\x05VALUE\x10\x03\x12\t\n" +
	"\x05LEASE\x10\x04B\x0e\n" +
	"\ftarget_union\"\xb0\x01\n" +
	"\x02Op\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.raftpb.Op.OpTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\trange_end\x18\x04 \x01(\tR\brangeEnd\x12\x14\n" +
	"\x05lease\x18\x05 \x01(\x03R\x05lease\"(\n" +
	"\x06OpType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\t\n" +
	"\x05RANGE\x10\x02\"\xc3\x02\n" +
	"\rStoreSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12:\n" +
	"\akv_data\x18\x02 \x03(\v2!.raftpb.StoreSnapshot.KvDataEntryR\x06kvData\x129\n" +
	"\x06leases\x18\x03 \x03(\v2!.raftpb.StoreSnapshot.LeasesEntryR\x06leases\x1aP\n" +
	"\vKvDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.raftpb.KeyValueProtoR\x05value:\x028\x01\x1aM\n" +
	"\vLeasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.raftpb.LeaseProtoR\x05value:\x028\x01\"\xb3\x01\n" +
	"\rKeyValueProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12'\n" +
	"\x0fcreate_revision\x18\x03 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x04 \x01(\x03R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\x03R\x05lease\"s\n" +
	"\n" +
	"LeaseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\x12/\n" +
	"\x14grant_time_unix_nano\x18\x03 \x01(\x03R\x11grantTimeUnixNano\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keysB!Z\x1fmetaStore/internal/proto;raftpbb\x06proto3"

var (
	file_internal_proto_raft_proto_rawDescOnce sync.Once
	file_internal_proto_raft_proto_rawDescData []byte
)

func file_internal_proto_raft_proto_rawDescGZIP() []byte {
	file_internal_proto_raft_proto_rawDescOnce.Do(func() {
		file_internal_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_raft_proto_rawDesc), len(file_internal_proto_raft_proto_rawDesc)))
	})
	return file_internal_proto_raft_proto_rawDescData
}

var file_internal_proto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_raft_proto_goTypes = []any{
	(Compare_CompareResult)(0), // 0: raftpb.Compare.CompareResult
	(Compare_CompareTarget)(0), // 1: raftpb.Compare.CompareTarget
	(Op_OpType)(0),             // 2: raftpb.Op.OpType
	(*RaftMessage)(nil),        // 3: raftpb.RaftMessage
	(*BatchOperation)(nil),     // 4: raftpb.BatchOperation
	(*RaftOperation)(nil),      // 5: raftpb.RaftOperation
	(*Compare)(nil),            // 6: raftpb.Compare
	(*Op)(nil),                 // 7: raftpb.Op
	(*StoreSnapshot)(nil),      // 8: raftpb.StoreSnapshot
	(*KeyValueProto)(nil),      // 9: raftpb.KeyValueProto
	(*LeaseProto)(nil),         // 10: raftpb.LeaseProto
	nil,                        // 11: raftpb.StoreSnapshot.KvDataEntry
	nil,                        // 12: raftpb.StoreSnapshot.LeasesEntry
}
var file_internal_proto_raft_proto_depIdxs = []int32{
	5,  // 0: raftpb.RaftMessage.single:type_name -> raftpb.RaftOperation
	4,  // 1: raftpb.RaftMessage.batch:type_name -> raftpb.BatchOperation
	5,  // 2: raftpb.BatchOperation.operations:type_name -> raftpb.RaftOperation
	6,  // 3: raftpb.RaftOperation.compares:type_name -> raftpb.Compare
	7,  // 4: raftpb.RaftOperation.then_ops:type_name -> raftpb.Op
	7,  // 5: raftpb.RaftOperation.else_ops:type_name -> raftpb.Op
	0,  // 6: raftpb.Compare.result:type_name -> raftpb.Compare.CompareResult
	1,  // 7: raftpb.Compare.target:type_name -> raftpb.Compare.CompareTarget
	2,  // 8: raftpb.Op.type:type_name -> raftpb.Op.OpType
	11, // 9: raftpb.StoreSnapshot.kv_data:type_name -> raftpb.StoreSnapshot.KvDataEntry
	12, // 10: raftpb.StoreSnapshot.leases:type_name -> raftpb.StoreSnapshot.LeasesEntry
	9,  // 11: raftpb.StoreSnapshot.KvDataEntry.value:type_name -> raftpb.KeyValueProto
	10, // 12: raftpb.StoreSnapshot.LeasesEntry.value:type_name -> raftpb.LeaseProto
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_proto_raft_proto_init() }
func file_internal_proto_raft_proto_init() {
	if File_internal_proto_raft_proto != nil {
		return
	}
	file_internal_proto_raft_proto_msgTypes[0].OneofWrappers = []any{
		(*RaftMessage_Single)(nil),
		(*RaftMessage_Batch)(nil),
	}
	file_internal_proto_raft_proto_msgTypes[3].OneofWrappers = []any{
		(*Compare_Version)(nil),
		(*Compare_CreateRevision)(nil),
		(*Compare_ModRevision)(nil),
		(*Compare_Value)(nil),
		(*Compare_Lease)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_raft_proto_rawDesc), len(file_internal_proto_raft_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_raft_proto_goTypes,
		DependencyIndexes: file_internal_proto_raft_proto_depIdxs,
		EnumInfos:         file_internal_proto_raft_proto_enumTypes,
		MessageInfos:      file_internal_proto_raft_proto_msgTypes,
	}.Build()
	File_internal_proto_raft_proto = out.File
	file_internal_proto_raft_proto_goTypes = nil
	file_internal_proto_raft_proto_depIdxs = nil
}
